
export const states = new Map([
    ['Albania', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:18,}],
  ['Andorra', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:18,}],
  ['Austria', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 16, license: 17, dropout: 15, supervised:17,}],
  ['Belgium', { consent: 18, gambling: 21, marriage: 18, drinkingAlcohol: 16, license: 18, dropout: 18, supervised:18,}],
  ['Bosnia and Herzegovina', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:18,}],
  ['Bulgaria', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:18,}],
  ['Croatia', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:18,}],
  ['Cyprus', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:18,}],
  ['Czechia', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:18,}],
  ['Denmark', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:17,}],
  ['Estonia', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:16,}],
  ['Finland', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:17,}],
  ['France', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:15,}],
  ['Germany', { consent: 18, gambling: 21, marriage: 18, drinkingAlcohol: 16, license: 18, dropout: 18, supervised:18,}],
  ['Greece', { consent: 18, gambling: 21, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:17,}],
  ['Hungary', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:17,}],
  ['Iceland', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:18,}],
  ['Ireland', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:18,}],
  ['Italy', { consent: 16, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:17,}],
  ['Kosovo', { consent: 16, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:18,}],
  ['Latvia', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:18,}],
  ['Liechtenstein', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 16, license: 18, dropout: 15, supervised:18,}],
  ['Lithuania', { consent: 18, gambling: 21, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:15,}],
  ['Luxembourg', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 16, license: 18, dropout: 18, supervised:18,}],
  ['Malta', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:18,}],
  ['Moldova', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:18,}],
  ['Monaco', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:18,}],
  ['Montenegro', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:16,}],
  ['Netherlands', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:17,}],
  ['North Macedonia', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 18, supervised:16,}],
  ['Norway', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:18,}],
  ['Poland', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:18,}],
  ['Portugal', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 18, supervised:18,}],
  ['Romania', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:18,}],
  ['San Marino', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 16, license: 18, dropout: 16, supervised:18,}],
  ['Serbia', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 14, supervised:17,}],
  ['Slovakia', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:17,}],
  ['Slovenia', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 15, supervised:18,}],
  ['Spain', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:18,}],
  ['Sweden', { consent: 18, gambling: 20, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 16, supervised:16,}],
  ['Switzerland', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 16, license: 18, dropout: 15, supervised:18,}],
  ['Ukraine', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 18, dropout: 17, supervised:18,}],
  ['England', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 16, license: 17, dropout: 16, supervised:18,}],
  ['Scotland', { consent: 18, gambling: 18, marriage: 16, drinkingAlcohol: 16, license: 17, dropout: 16, supervised:18,}],
  ['Wales', { consent: 18, gambling: 18, marriage: 18, drinkingAlcohol: 16, license: 17, dropout: 16, supervised:18,}],
  ['Northern Ireland', { consent: 17, gambling: 18, marriage: 18, drinkingAlcohol: 18, license: 17, dropout: 16, supervised:18,}],
  ]);
  
  export const stateAbbreviations = {
  'Albania': 'AL',
  'Andorra': 'AD',
  'Austria': 'AT',
  'Belgium': 'BE',
  'Bosnia and Herzegovina': 'BA',
  'Bulgaria': 'BG',
  'Croatia': 'HR',
  'Cyprus': 'CY',
  'Czechia': 'CZ',
  'Denmark': 'DK',
  'Estonia': 'EE',
  'Finland': 'FI',
  'France': 'FR',
  'Germany': 'DE',
  'Greece': 'GR',
  'Hungary': 'HU',
  'Iceland': 'IS',
  'Ireland': 'IE',
  'Italy': 'IT',
  'Kosovo': 'XK',
  'Latvia': 'LV',
  'Liechtenstein': 'LI',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Malta': 'MT',
  'Moldova': 'MD',
  'Monaco': 'MC',
  'Montenegro': 'ME',
  'Netherlands': 'NL',
  'North Macedonia': 'MK',
  'Norway': 'NO',
  'Poland': 'PL',
  'Portugal': 'PT',
  'Romania': 'RO',
  'San Marino': 'SM',
  'Serbia': 'RS',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Spain': 'ES',
  'Sweden': 'SE',
  'Switzerland': 'CH',
  'Ukraine': 'UA',
  'England': 'ENG',
  'Scotland': 'SCT',
  'Wales': 'WLS',
  'Northern Ireland': 'NIR',
  
  };

  export const stateAbbrArray = [
    ['AL', 'AD', 'AT', 'BE', 'BA', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IS', 'IE', 'IT', 'XK', 'LV', 'LI', 'LT', 'LU', 'MT', 'MD', 'MC', 'ME', 'NL', 'MK', 'NO', 'PL', 'PT', 'RO', 'SM', 'RS', 'SK', 'SI', 'ES', 'SE', 'CH', 'UA', 'ENG','SCT','WLS','NIR']
  ];